id: doany-chief-of-staff
namespace: doany.app
description: "Autonomous Chief of Staff: Handles Ops and Admin work simultaneously"

inputs:
  - id: command
    type: STRING
    defaults: "The server is returning 503 errors. Fix it and create a generic incident task in Notion."

triggers:
  - id: external_api_trigger
    type: io.kestra.plugin.core.trigger.Webhook
    key: "hackathon-secret-123"

tasks:
  # ------------------------------------------------------------------
  # 1. THE BRAIN: Parse Intent
  # ------------------------------------------------------------------
  - id: parse_intent
    type: io.kestra.plugin.scripts.python.Script
    containerImage: python:3.11-slim
    beforeCommands:
      - pip install kestra
    script: |
      from kestra import Kestra
      command = "{{ inputs.command }}".lower()
      
      actions = []
      
      # Robust Keyword Matching for Demo Reliability
      if "fix" in command or "server" in command or "500" in command or "503" in command:
          actions.append("DEVOPS_FIX")
      
      if "log" in command or "notion" in command or "task" in command or "create" in command:
          actions.append("NOTION_UPDATE")

      print(f"🧠 BRAIN: Detected Intent -> {actions}")
      Kestra.outputs({"actions": actions})

  # ------------------------------------------------------------------
  # 2. PARALLEL EXECUTION (Ops & Admin at the same time)
  # ------------------------------------------------------------------
  - id: execute_parallel
    type: io.kestra.plugin.core.flow.Parallel
    tasks:
    
      # === AGENT A: THE ENGINEER (DevOps) ===
      - id: devops_agent
        type: io.kestra.plugin.core.flow.If
        condition: "{{ outputs.parse_intent.vars.actions contains 'DEVOPS_FIX' }}"
        then:
          - id: run_fix
            type: io.kestra.plugin.scripts.python.Script
            containerImage: python:3.11-slim
            script: |
              import time
              print("🛠️ DEVOPS AGENT: Connected to Kubernetes Cluster (us-east-1)")
              time.sleep(1)
              print("🔍 DIAGNOSIS: Pods are crash-looping due to OOM (Out of Memory).")
              time.sleep(1)
              print("🚀 ACTION: Scaling up replicas to 10 and increasing memory limits...")
              time.sleep(1)
              print("✅ SUCCESS: Health probes passing. Latency stabilized.")

      # === AGENT B: THE ADMIN (Notion) ===
      - id: notion_agent
        type: io.kestra.plugin.core.flow.If
        condition: "{{ outputs.parse_intent.vars.actions contains 'NOTION_UPDATE' }}"
        then:
          - id: create_notion_page
            type: io.kestra.plugin.scripts.python.Script
            containerImage: python:3.11-slim
            beforeCommands:
              - pip install requests
            script: |
              import requests
              import json
              import os
              
              # --- CONFIGURATION (Use environment variables for secrets) ---
              NOTION_TOKEN = os.getenv("NOTION_TOKEN", "your-notion-token-here")
              DATABASE_ID = os.getenv("NOTION_DATABASE_ID", "your-database-id-here")
              
              print(f"📝 NOTION AGENT: Authenticating...")

              headers = {
                  "Authorization": f"Bearer {NOTION_TOKEN}",
                  "Content-Type": "application/json",
                  "Notion-Version": "2022-06-28"
              }
              
              # --- RICH CONTENT PAYLOAD ---
              data = {
                  "parent": {"database_id": DATABASE_ID},
                  "properties": {
                      "Name": {"title": [{"text": {"content": "🚨 Auto-Fix: Server Outage"}}]}
                  },
                  "children": [
                      {
                          "object": "block",
                          "type": "heading_2",
                          "heading_2": {"rich_text": [{"text": {"content": "⚠️ Incident Report"}}]}
                      },
                      {
                          "object": "block",
                          "type": "paragraph",
                          "paragraph": {"rich_text": [{"text": {"content": "The autonomous agent detected a Critical 503 Error at 04:52 UTC. Traffic was dropping packets."}}]}
                      },
                      {
                          "object": "block",
                          "type": "heading_3",
                          "heading_3": {"rich_text": [{"text": {"content": "Actions Taken"}}]}
                      },
                      {
                          "object": "block",
                          "type": "to_do",
                          "to_do": {
                              "rich_text": [{"text": {"content": "Scaled Kubernetes Cluster"}}],
                              "checked": True
                          }
                      },
                      {
                          "object": "block",
                          "type": "to_do",
                          "to_do": {
                              "rich_text": [{"text": {"content": "Notified DevOps Team"}}],
                              "checked": True
                          }
                      }
                  ]
              }
              
              # --- EXECUTE ---
              try:
                  print("🚀 SENDING RICH REPORT TO NOTION...")
                  response = requests.post("https://api.notion.com/v1/pages", headers=headers, json=data)
                  
                  if response.status_code == 200:
                      print(f"✅ SUCCESS: Created Full Incident Report! (ID: {response.json().get('id')})")
                  else:
                      print(f"❌ ERROR: Notion API returned {response.status_code}")
                      print(response.text)
                      exit(1)
              except Exception as e:
                  print(f"❌ CRITICAL FAILURE: {str(e)}")
                  exit(1)